spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


  datasource:
    url: jdbc:mysql://localhost:3306/hh
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8095

savePath: "C:\\Trans\\"
